### ISSUE TITLE
Bootstrap 4?

### ISSUE THREAD

**Issue by cquillen2003** [shlomiassaf/angular2-modal#32]
Does this work with Bootstrap 4?

**Comment by shlomiassaf** [comment]
Never tested it, I need to see the change log for BS4

It should support it, but if BS4 use's Tether for modal windows it will not behave the same.

**Comment by ellern** [comment]
I'm using it with BS4, no problem so far

**Comment by FriOne** [comment]
Bootstrap 4 uses `show` class instead of `in`, so to make it work you need to add this:
```scss
.modal {

  &.in {
    opacity: 1;

    .modal-dialog {
      transform: translate(0, 0);
    }
  }
}

.modal-backdrop {

  &.in {
    opacity: $modal-backdrop-opacity;
  }
}
```
